# Default total build time is 10m, which isn't always enough.
timeout: 1800s

options:
  # Allow images to build more quickly.
  machineType: 'N1_HIGHCPU_8'

############################################################################
# Create project-specific customized builder images.
############################################################################

steps:
# Build golang-cbif container. Useful golang builds and tests.
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--tag=gcr.io/$PROJECT_ID/golang-cbif:1.20',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/build-images/golang-cbif:1.20',
    '--file=Dockerfile.golang', '.'
  ]

# Build gcloud-jsonnet-cbif image combining: gcloud, jsonnet, and cbif.
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--tag=gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif:1.1',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/build-images/gcloud-jsonnet-cbif:1.1',
    '--file=Dockerfile.jsonnet', '.'
  ]
  waitFor: ['-']

# Build epoxy-images image
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--tag=gcr.io/$PROJECT_ID/epoxy-images:1.1',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/build-images/epoxy-images:1.1',
    '--file=Dockerfile.epoxy-images', '.'
  ]
  waitFor: ['-']

# Build siteinfo-cbif image. Used by siteinto repository builds.
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--tag=gcr.io/$PROJECT_ID/siteinfo-cbif:1.1',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/build-images/siteinfo-cbif:1.1',
    '--file=Dockerfile.siteinfo', '.'
  ]
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/golang-cbif:1.20'
- 'gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif:1.1'
- 'gcr.io/$PROJECT_ID/epoxy-images:1.1'
- 'gcr.io/$PROJECT_ID/siteinfo-cbif:1.1'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/build-images/golang-cbif:1.20'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/build-images/gcloud-jsonnet-cbif:1.1'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/build-images/epoxy-images:1.1'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/build-images/siteinfo-cbif:1.1'

