apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-notifier
spec:
  notification:
    filter: build.status == Build.Status.FAILURE
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://{{PROJECT}}-notifiers-config/slack-message-template.json
    params:
      buildStatus: $(build.status)
  secrets:
  - name: webhook-url
    value: projects/{{PROJECT}}/secrets/cloud-build-slack-webhook-url/versions/latest

